### ISSUE TITLE
challenges/01-responsive-web-design/css-flexbox

### ISSUE THREAD

**Issue by juzhiyuan** [FreeCodeCampChina/curriculum-cn#5]
Translation section:
https://github.com/FreeCodeCampChina/curriculum-cn/blob/dev/challenges/01-responsive-web-design/css-flexbox.json

**Comment by huluoyang** [comment]
@juzhiyuan 抱歉，我们新开了 challenges 仓库来专门做翻译，此仓库不再用作翻译。

详情请传送到：https://github.com/freecodecampchina/challenges

**Comment by huluoyang** [comment]
@juzhiyuan 由于没有你的微信，所以通知不及时，请加我的微信号：huluoyang001，我拉你进翻译写作群。
