### ISSUE TITLE
A link links another report

### ISSUE THREAD

**Issue by stevending1st** [FreeCodeCampChina/curriculum-cn#6]
**Describe the bug**
In this readme.md : 
 "翻译指南" >>"工作流程" >>"Translation request"
this link links another report.

**To Reproduce**
1.Please Change it, thanks.
2.Please delete an issues reported by me, this is link: https://github.com/FreeCodeCampChina/curriculum/issues/4

**Comment by S1ngS1ng** [comment]
Fixed. Thanks
